### PR TITLE
Make readme more readable

### PR DESCRIPTION
**Pull request by Samisafool**
WIP, but when merging please squash

You can see demo https://github.com/Samisafool/Personal-Voice-Assistent

### CODE REVIEW

**Comment by Samisafool** [comment]
I guess I forgot to mark as draft, please use `git revert 67b0ffe0a98a483690063106fca213f7498c3191` and push, @Cyborgscode

**Comment by Cyborgscode** [comment]
As there is no local git repo here, how can we archive this on the webui... and just to state the obvious, this isn't helpfull:  

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit

"You can revert a specific commit to remove its changes from your branch."  Ok, GitHub Managers, we can revert, and HOW?!?!?! :D

**Comment by Samisafool** [comment]
What do you mean by local git repo? Surely you do have a local git copy that you use to do `git push` right?

In that case use the below command

`git revert 67b0ffe0a98a483690063106fca213f7498c3191`

then `git push`

And in the webui there is a button for merging, click on the dropdown and hit `squash and merge`

But currently i marked it as draft, i will unmark

**Comment by Samisafool** [comment]
And in the docs, click on the `windows` tab

**Comment by Samisafool** [comment]
image

image

**Comment by Cyborgscode** [comment]
Thats for a local Git Client, not for the Git-WebUI. It seems to be time to switch to a local git client.

**Comment by Samisafool** [comment]
I suppose you forgot to squash. That added 8 extra commits to the merge history, but overall nothing major.

And by github webui you mean github.dev, or github.com?

And by local git client, you can use the `git` command I posted earlier. It's good to learn it.

**Comment by Cyborgscode** [comment]
I just used guihub.coms interface.. there no local git clone yet ;) Using git isn't and issue, it simple wasn't necessary yet :)

**Comment by Samisafool** [comment]
You mean to say you have coded all of this in github webui???? Wow, impressive

If you want I can suggest VSCodium for a text editor

And just learn the git command, a git client isn't necessary

**Comment by Cyborgscode** [comment]
of course not, as usual in gedit ;)

**Comment by Cyborgscode** [comment]
BTW.. the next feature release will break things a lot, a branch may be needed.

**Comment by Samisafool** [comment]
Can I post this in https://reddit.com/r/programminghumor?

This guy made a whole voice assistant in java

**Comment by Cyborgscode** [comment]
sure , it's true :D honestly.

**Pull request merged**
